name: nurai
description: A calm, mobile-first Islamic app for Quran reading and reflection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quran/final/quran_ar_tr.json
    - assets/quran/meta/surahs.json
    - assets/quran/meta/juz_ranges.json

  fonts:
  - family: Amiri
    fonts:
      - asset: assets/fonts/Amiri-Regular.ttf
      - asset: assets/fonts/Amiri-Bold.ttf
        weight: 700

  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather.ttf

  - family: Inter
    fonts:
      - asset: assets/fonts/Inter.ttf


